### ISSUE TITLE
AttributeError: 'module' object has no attribute 'require_version'

### ISSUE THREAD

**Issue by buxx** [sdrelton/cryptocoin-indicator#4]
Hello,

When execute script with python2, i got:

```
python cryptocoin-indicator.py
<module 'gi' from '/home/bux/Projets/cryptocoin-indicator/venv2.7/local/lib/python2.7/site-packages/gi/__init__.pyc'>
Traceback (most recent call last):
  File "cryptocoin-indicator.py", line 8, in <module>
    gi.require_version('Gtk', '3.0')
AttributeError: 'module' object has no attribute 'require_version'
```

And with python3:

```
python cryptocoin-indicator.py 
Traceback (most recent call last):
  File "cryptocoin-indicator.py", line 6, in <module>
    import gi
  File "/home/bux/Projets/cryptocoin-indicator/venv3.5/lib/python3.5/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
```

Thank's.

**Comment by sdrelton** [comment]
Hey,

According to this you need to install python-gobject

https://github.com/enkore/i3pystatus/issues/314

Let me know if you have any other trouble!

Cheers,
Sam
________________________________________

**Comment by buxx** [comment]
Hello,

Actually, i already have  ̀python-gobject` installed on my Ubuntu 16.04. Tested without virtual environment: No bugs!

Bux.

**Comment by sdrelton** [comment]
Great! Glad it's working for you now. Shall I close the issue?
________________________________________

**Comment by sdrelton** [comment]
Rereading your comment I believe the issue is now fixed, so I'll close it. Let me know if you have any further problems!
